### ISSUE TITLE
Unable to release GWT Samples for 2.4.0

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere-samples#55]
Strange GWT compiler error, so the sample are excluded from the release.
```java
[INFO] --- gwt-maven-plugin:2.5.1:compile (default) @ gwt20-managed-rpc ---
    [INFO] Compiling module org.atmosphere.samples.GwtRpcDemo
    [INFO]    [ERROR] An internal compiler exception occurred
    [INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
    [INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:109)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:276)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:116)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:65)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:116)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JDeclarationStatement.traverse(JDeclarationStatement.java:48)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:170)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:336)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:83)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:133)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:82)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:434)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:403)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:900)
    [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:625)
    [INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:640)
    [INFO] 	at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:33)
    [INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:278)
    [INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
    [INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:141)
    [INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:232)
    [INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:198)
    [INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
    [INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
    [INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
    [INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:177)
    [INFO] Caused by: java.lang.NoSuchMethodError: com.google.gwt.user.rebind.rpc.SerializableTypeOracleBuilder.<init>(Lcom/google/gwt/core/ext/TreeLogger;Lcom/google/gwt/core/ext/GeneratorContext;)V
    [INFO] 	at org.atmosphere.gwt20.rebind.SerializerGenerator.generateIncrementally(SerializerGenerator.java:87)
    [INFO] 	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:651)
    [INFO] 	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:41)
    [INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
    [INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
    [INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:265)
    [INFO] 	at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:91)
    [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleGwtCreate(UnifyAst.java:355)
    [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:433)
    [INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:237)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:243)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    [INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    [INFO] 	... 37 more
    [INFO]       [ERROR] at GwtRpcDemo.java(83): GWT.create(RPCSerializer.class)
    [INFO]          com.google.gwt.dev.jjs.ast.JMethodCall
    [INFO]       [ERROR] at GwtRpcDemo.java(83): (RPCSerializer) GWT.create(RPCSerializer.class)
    [INFO]          com.google.gwt.dev.jjs.ast.JCastOperation
    [INFO]       [ERROR] at GwtRpcDemo.java(83): RPCSerializer rpc_serializer = (RPCSerializer) GWT.create(RPCSerializer.class)
    [INFO]          com.google.gwt.dev.jjs.ast.JDeclarationStatement
    [INFO]       [ERROR] at GwtRpcDemo.java(51): {
    [INFO]   GWT.setUncaughtExceptionHandler(new GwtRpcDemo$1(this));
    [INFO]   HorizontalPanel buttons = new HorizontalPanel();
    [INFO]   final TextBox messageInput = new TextBox();
```

**Comment by elakito** [comment]
@jfarcand i'm closing this ticket, as we don't seem to have this problem any more.

**Comment by jfarcand** [comment]
+1
