### ISSUE TITLE
JSR-356 support unavailable

### ISSUE THREAD

**Issue by Muzeffer** [Atmosphere/atmosphere-samples#65]
When I'm running **atmosphere-socketio-chat** in the Tomcat 7.0.68,It appears _**javax.servlet.ServletException**_.

> javax.servlet.ServletException: Not running on Jetty, JSR-356 support unavailable
	at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.onStartup(WebSocketServerContainerInitializer.java:146)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5573)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1572)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1562)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

> javax.servlet.ServletException: Not running on Jetty, JSR-356 support unavailable
	at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.onStartup(WebSocketServerContainerInitializer.java:146)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5573)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1259)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1998)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[http://stackoverflow.com/questions/32202344/javax-servlet-servletexception-not-running-on-jetty-jsr-356-support-unavailabl](url)
I find this and it's not helping.

**And the environment is : 
JRE 1.8
 Tomcat 7.0.68**

Andbody can help me ?

**Comment by elakito** [comment]
I suspect either some interfering jar is included in your application or a required jars/configuration is missing.
The atmosphere-scoketio-chat sample itself runs fine on tomcat7 with jdk8. (e.g., this sample runs fine when started with an embedded tomcat7 via mvn tomcat7:run)
